// --------------------------------------------------------------------------

#define	HYPERCALLOPERATION_ARM_PSR		0x02000000

#define	HYPERCALLARGUMENT_ARM_PSR_CURRENT	0x00100000
#define	HYPERCALLARGUMENT_ARM_PSR_SAVED		0x00200000
#define	HYPERCALLARGUMENT_ARM_PSR_MODE		0x00001000
#define	HYPERCALLARGUMENT_ARM_PSR_EXSTATE	0x00002000
#define	HYPERCALLARGUMENT_ARM_PSR_SIMD		0x00004000
#define	HYPERCALLARGUMENT_ARM_PSR_FLAGS		0x00008000
#define	HYPERCALLARGUMENT_ARM_PSR_ALLBITS	0x0000f000

#define	HYPERCALLARGUMENT_ARM_PSR_CPSIX		0x00400000
#define	HYPERCALLARGUMENT_ARM_PSR_CPSIE_I	0x00010000
#define	HYPERCALLARGUMENT_ARM_PSR_CPSID_I	0x00020000
#define	HYPERCALLARGUMENT_ARM_PSR_CPSIE_F	0x00040000
#define	HYPERCALLARGUMENT_ARM_PSR_CPSID_F	0x00080000

// -------------------------------------

#define	HYPERCALL_CPSIE_I			(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_PSR | HYPERCALLARGUMENT_ARM_PSR_CPSIX | HYPERCALLARGUMENT_ARM_PSR_CPSIE_I)
#define	HYPERCALL_CPSID_I			(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_PSR | HYPERCALLARGUMENT_ARM_PSR_CPSIX | HYPERCALLARGUMENT_ARM_PSR_CPSID_I)
#define	HYPERCALL_CPSIE_F			(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_PSR | HYPERCALLARGUMENT_ARM_PSR_CPSIX | HYPERCALLARGUMENT_ARM_PSR_CPSIE_F)
#define	HYPERCALL_CPSID_F			(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_PSR | HYPERCALLARGUMENT_ARM_PSR_CPSIX | HYPERCALLARGUMENT_ARM_PSR_CPSID_F)

#define	HYPERCALL_CPSR_READ			(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_PSR | HYPERCALLARGUMENT_ARM_PSR_CURRENT | HYPERCALLARGUMENT_ARM_PSR_ALLBITS | HYPERCALLDIRECTION_READ)
#define	HYPERCALL_CPSR_WRITE			(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_PSR | HYPERCALLARGUMENT_ARM_PSR_CURRENT | HYPERCALLARGUMENT_ARM_PSR_ALLBITS | HYPERCALLDIRECTION_WRITE)
#define	HYPERCALL_SPSR_READ			(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_PSR | HYPERCALLARGUMENT_ARM_PSR_SAVED | HYPERCALLARGUMENT_ARM_PSR_ALLBITS | HYPERCALLDIRECTION_READ)
#define	HYPERCALL_SPSR_WRITE			(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_PSR | HYPERCALLARGUMENT_ARM_PSR_SAVED | HYPERCALLARGUMENT_ARM_PSR_ALLBITS | HYPERCALLDIRECTION_WRITE)

// --------------------------------------------------------------------------

#define	HYPERCALLOPERATION_ARM_COPROC		0x01000000

#define	HYPERCALLARGUMENT_ARM_COPROC_CRN	0x00f00000
#define	HYPERCALLARGUMENT_ARM_COPROC_CRM	0x000f0000
#define	HYPERCALLARGUMENT_ARM_COPROC_IM0	0x0000f000
#define	HYPERCALLARGUMENT_ARM_COPROC_IM1	0x00000f00
#define	HYPERCALLARGUMENT_ARM_COPROC_REG	0x000000f0

// --------------------------------------------------------------------------

#define	HYPERCALLOPERATION_ARM_MODESWITCH	0x04000000

#define HYPERCALLARGUMENT_ARM_MODE_LR_SP	0x00100000
#define HYPERCALLARGUMENT_ARM_MODE_LR_OFFSET	0x00200000
#define HYPERCALLARGUMENT_ARM_MODE_LDM		0x00400000

#define	HYPERCALL_SPR0_LRPC			(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_MODESWITCH | HYPERCALLARGUMENT_ARM_MODE_LR_SP)
#define	HYPERCALL_LR_EXCEPTION_RETURN(offset)	(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_MODESWITCH | HYPERCALLARGUMENT_ARM_MODE_LR_OFFSET | offset)
#define	HYPERCALL_LDM_EXCEPTION_RETURN(regbits)	(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_MODESWITCH | HYPERCALLARGUMENT_ARM_MODE_LDM | regbits)

// --------------------------------------------------------------------------

#define	HYPERCALLOPERATION_ARM_BANKED_REG	0x08000000

#define HYPERCALLARGUMENT_ARM_BANKED_LDM	0x00100000
#define HYPERCALLARGUMENT_ARM_BANKED_STM	0x00200000
#define HYPERCALLARGUMENT_ARM_BANKED_LDRT	0x00400000
#define HYPERCALLARGUMENT_ARM_BANKED_STRT	0x00400000

#define	HYPERCALL_LDM_USER(regbits)		(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_BANKED_REG | HYPERCALLARGUMENT_ARM_BANKED_LDM | regbits)
#define	HYPERCALL_STM_USER(regbits)		(HYPERCALLTYPE_ARCHITECTURE | HYPERCALLOPERATION_ARM_BANKED_REG | HYPERCALLARGUMENT_ARM_BANKED_STM | regbits)

// --------------------------------------------------------------------------
