// --------------------------------------------------------------------------

#define	HYPERCALLOPERATION_EXEC_CONTROL		0x01000000

#define	HYPERCALLARGUMENT_EXEC_SLEEP		0x00000010

#define	HYPERCALL_SLEEP				(HYPERCALLTYPE_EMULATION | HYPERCALLOPERATION_EXEC_CONTROL | HYPERCALLARGUMENT_EXEC_SLEEP)

// --------------------------------------------------------------------------

#define	HYPERCALLOPERATION_INTERFACE_CONTROL	0x02000000

#define	HYPERCALLARGUMENT_IFACE_QUERY_ARCHPAGE	0x00000010
#define	HYPERCALLARGUMENT_IFACE_ANNOUNCE_TRACE	0x00000020

#define	HYPERCALL_QUERY_ARCHPAGE		(HYPERCALLTYPE_EMULATION | HYPERCALLOPERATION_INTERFACE_CONTROL | HYPERCALLARGUMENT_IFACE_QUERY_ARCHPAGE)
#define	HYPERCALL_ANNOUNCE_TRACEBUFFER		(HYPERCALLTYPE_EMULATION | HYPERCALLOPERATION_INTERFACE_CONTROL | HYPERCALLARGUMENT_IFACE_ANNOUNCE_TRACE)

// --------------------------------------------------------------------------

#define	HYPERCALLOPERATION_PARAVIRT_DEVICE	0x04000000

// ...
