ifeq ($(O),)
$(error No output directory. Do not use Makefile.output directly!)
endif

$(info Build Directory: $(O))
$(info Identified CBI: $(CBI))

TARGET_BUILD_CTLS := $(O)/.src-core $(O)/.src-xml $(O)/Makefile
PWD := $(shell pwd)
PWD_CORE := $(dir $(PWD))core

BLOBFILES := $(O)/$(CBI).elf $(shell tools/blobfiles "$(O)")

$(O)/Makefile: Target-Makefile
	cp $^ $@

$(O)/.src-xml: $(PWD)
	ln -sfnT $(PWD) $@

$(O)/.src-core: $(PWD_CORE)
	ln -sfnT $(PWD_CORE) $@

$(O)/.makeconf_checked: $(O)/scenario.xml precompilation precompilation_$(CBI) $(XML_LIBRARY) | $(TARGET_BUILD_CTLS)
	./precompilation $(O)
	@if [ $(O)/Makeconf -nt $< ]; then \
		$(MAKE) -C ../core O=$(O); \
	fi
	@touch $@

$(O)/scenario_expanded.xml: $(O)/scenario.xml $(O)/.makeconf_checked expand $(XML_LIBRARY)
	./expand $(O)

$(O)/scenario_reparented.xml: $(O)/scenario_expanded.xml reparent $(XML_LIBRARY)
	./reparent $(O)

$(O)/scenario_config.c: $(O)/scenario_reparented.xml generate_config generate_config_$(CBI)
	./generate_config $(O) 1

$(O)/scenario_config.xo: $(O)/scenario_config.c $(O)/invoke_gcc.cmd config.lds
	@INVOKE_CMD=$$(< $(filter %.cmd,$^)); \
	echo "$$INVOKE_CMD -Werror -fno-zero-initialized-in-bss -Wl,-T$(filter %.lds,$^),--unresolved-symbols=ignore-all $< -o $@"; \
	$$INVOKE_CMD -Werror -fno-zero-initialized-in-bss -Wl,-T$(filter %.lds,$^),--unresolved-symbols=ignore-all $< -o $@

$(O)/scenario_measured.xml: $(O)/scenario_reparented.xml $(O)/scenario_config.xo $(BLOBFILES) measure $(XML_LIBRARY)
	./measure $(O)

# $(O)/scenario_p_laidout.xml

$(O)/scenario_v_laidout.xml: $(O)/scenario_measured.xml layouter $(XML_LIBRARY)
	./layouter $(O)

$(O)/scenario_pagetables.xml: $(O)/scenario_v_laidout.xml pagetables $(XML_LIBRARY)
	./pagetables $(if $(V),-v,) $(O)

$(O)/scenario_config_real.c: $(O)/scenario_pagetables.xml generate_config generate_config_$(CBI)
	./generate_config $(O) 2

$(O)/scenario_config_real.xo: $(O)/scenario_config_real.c $(O)/invoke_gcc.cmd config.lds
	@INVOKE_CMD=$$(< $(filter %.cmd,$^)); \
	echo "$$INVOKE_CMD -Werror -fno-zero-initialized-in-bss -Wl,-T$(O)/config_base.lds,-T$(filter %.lds,$^) $< -o $@"; \
	$$INVOKE_CMD -Werror -fno-zero-initialized-in-bss -Wl,-T$(O)/config_base.lds,-T$(filter %.lds,$^) $< -o $@

$(O)/image: $(O)/scenario_config_real.xo $(O)/scenario_pagetables.xml $(O)/$(CBI).elf combine
	./combine $(O)

all: $(O)/image
