#ifndef	_PHIDIAS_ASM_LAPIC_H_
#define	_PHIDIAS_ASM_LAPIC_H_

# define	LAPICREG_APIC_ID		0x020
# define	LAPICREG_APIC_VERSION		0x030
# define	LAPICREG_EOI			0x0b0
# define	LAPICREG_DESTINATION		0x0d0
# define	LAPICREG_DEST_MODE		0x0e0
# define	LAPICREG_SPURIOUS		0x0f0
# define	LAPICREG_ICR_LOW		0x300
# define	LAPICREG_ICR_HIGH		0x310
# define	LAPICREG_LVT_TIMER		0x320
# define	LAPICREG_LVT_THERMAL		0x330
# define	LAPICREG_LVT_PERFCNT		0x340
# define	LAPICREG_LVT_LINT0		0x350
# define	LAPICREG_LVT_LINT1		0x360
# define	LAPICREG_LVT_ERROR		0x370
# define	LAPICREG_TIMER_INITIAL		0x380
# define	LAPICREG_TIMER_CURRENT		0x390
# define	LAPICREG_TIMER_DIVISOR		0x3e0

# define	LAPICLVT_MASK			0x10000

# define	IRQNO_LAPIC_TIMER		0xdd

# define	IOAPICREG_SEL			0x00
# define	IOAPICREG_DATA			0x10

# define	IOAPICREGWIN_ID			0x00
# define	IOAPICREGWIN_VERSION		0x01
# define	IOAPICREGWIN_ARB_ID		0x02
# define	IOAPICREGWIN_IOREDTBL		0x10

# define	IOAPIC_REDTBL_COUNT		24

# define	IRQNO_IOAPIC_BASE		0x30

#endif
