#ifndef	_PHIDIAS_ASM_MPCORE_H_
#define	_PHIDIAS_ASM_MPCORE_H_

# define	MPCORE_IRQCPU_BASE	0x0100
# define	MPCORE_IRQDIST_BASE	0x1000

# define	MPCORE_GLOBALTIMER_BASE			0x200
# define	MPCORE_GLOBALTIMER_VALUE_LOW		(MPCORE_GLOBALTIMER_BASE + 0x000)
# define	MPCORE_GLOBALTIMER_VALUE_HIGH		(MPCORE_GLOBALTIMER_BASE + 0x004)
# define	MPCORE_GLOBALTIMER_CONTROL		(MPCORE_GLOBALTIMER_BASE + 0x008)

# define	MPCORE_PRIVATETIMER_BASE		0x600
# define	MPCORE_PRIVATETIMER_LOAD		(MPCORE_PRIVATETIMER_BASE + 0x000)
# define	MPCORE_PRIVATETIMER_COUNTER		(MPCORE_PRIVATETIMER_BASE + 0x004)
# define	MPCORE_PRIVATETIMER_CONTROL		(MPCORE_PRIVATETIMER_BASE + 0x008)
# define	MPCORE_PRIVATETIMER_IRQ_STATUS		(MPCORE_PRIVATETIMER_BASE + 0x00c)

# define	MPCORE_PRIVATETIMER_CONTROL_ENABLE	0x0001
# define	MPCORE_PRIVATETIMER_CONTROL_AUTOLOAD	0x0002
# define	MPCORE_PRIVATETIMER_CONTROL_IRQ_ENABLE	0x0004
# define	MPCORE_PRIVATETIMER_CONTROL_PRESCALE(p)	((p) << 8)
# define	MPCORE_PRIVATETIMER_CONTROL_GET_PRESCALE(ctl)	(((ctl) >> 8) & 0xff)

#endif
